name: Automated Robot Tests

on:
  pull_request:
    branches: [ develop ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Execute tests
          uses: joonvena/robotframework-docker-action@v0.1
          env:
            BROWSER: chrome
            ROBOT_TESTS_DIR: ${{ /automated_tests }}
            ROBOT_REPORTS_DIR: ${{ github.workspace }}