name: Automated Robot Tests

on:
  pull_request:
    branches: [ develop ]


jobs:
  # setup-chromedriver:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - uses: nanasess/setup-chromedriver@master
  #     - run: |
  #         export DISPLAY=:99
  #         chromedriver --url-base=/wd/hub &
  #         sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

  automated-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: python -m pip install --upgrade pip robotframework robotframework-seleniumlibrary robotframework-requests
      # - name: Install Robot Dependencies
      #   run: pip install -r requirements.txt
      - name: Setup ChromeDriver
        run: |
          wget http://chromedriver.storage.googleapis.com/81.0.4044.69/chromedriver_mac64.zip
          unzip chromedriver_mac64.zip
          sudo mv chromedriver /usr/local/bin
          sudo chown root:root /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
      - name: Run Robot Tests
        run: robot automated_tests
         
  # robot-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Execute tests
  #       uses: joonvena/robotframework-docker-action@v0.1
  #       env:
  #         BROWSER: chrome
  #         ROBOT_TESTS_DIR: ${{ github.workspace }}/automated_tests
  #         ROBOT_REPORTS_DIR: ${{ github.workspace }}/automated_test_reports