name: Automated Robot Tests

on:
  pull_request:
    branches: [ develop, release ]


jobs:
  automated-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: python -m pip install --upgrade pip robotframework robotframework-seleniumlibrary robotframework-requests
      - name: Run Robot Tests
        run: robot automated_tests
      - name: Print Test Results
        # working-directory: automated_tests
        run: cat report.html