name: Automated Robot Tests

on:
  pull_request:
    branches: [ develop ]


jobs:
  automated-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies 
        run: |
        python -m pip install --upgrade pip
        pip install robotframework 
        pip install robotframework-seleniumlibrary 
        pip install robotframework-requests
      - name: Run Robot Tests
        run: robot automated_tests
         
  # robot-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Execute tests
  #       uses: joonvena/robotframework-docker-action@v0.1
  #       env:
  #         BROWSER: chrome
  #         ROBOT_TESTS_DIR: ${{ github.workspace }}/automated_tests
  #         ROBOT_REPORTS_DIR: ${{ github.workspace }}/automated_test_reports