name: Increment version number

on:
  push:
    branches: [ release ]


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Increment the package version 
        run: npm run increment